---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: load-selector
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: load
  namespaceSelector:
    matchNames:
      - load
  podMetricsEndpoints:
    - targetPort: metrics
      path: /metrics
      interval: 2s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: server-selector
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: server
  namespaceSelector:
    matchNames:
      - server
  podMetricsEndpoints:
    - targetPort: metrics
      path: /metrics
      interval: 2s
...
