apiVersion: v1
kind: Service
metadata:
  name: load
  labels:
    app: load
  namespace: load
spec:
  selector:
    app: load
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: metrics
    protocol: TCP
    port: 2112
    targetPort: metrics
