apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  server
    spec:
      containers:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - server
              topologyKey: kubernetes.io/hostname 
      restartPolicy: Always
