name: ci

on:
  push:
    branches:
      - main

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push GHCR load
        id: docker_build_ghcr
        uses: docker/build-push-action@v2
        with:
          context: .
          file: load/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/load:latest
      -
        name: Build and push GHCR server
        id: docker_build_ghcr
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/server:latest
