name: ci

on:
  push:
    branches:
      - main

jobs:
  container:
    strategy:
      matrix:
        img: [load, server]
        arch: [amd64, arm, arm64]
        os: [linux]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push GHCR load
        id: docker_build_ghcr_load
        uses: docker/build-push-action@v2
        with:
          file: "${{ matrix.img }}/Dockerfile"
          push: true
          platforms: ${{ matrix.arch }}
          build-args: |
            GOARCH=${{ matrix.arch }}
            GOOS=${{ matrix.os }}
            BUILDPLATFORM=linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.img }}:latest
